---
# tasks file for ansible-role-devops-docker-utils


#- name: copia credenciales de artifactory
#  template: src=dockercfg dest=/home/git/.dockercfg owner=centos group=centos

#- name: copia credenciales de artifactory
#  template: src=dockercfg dest=/root/.dockercfg owner=centos group=centos

- name: create docker-compose dir
  file: path="{{ devops_docker_utils.compose_dir }}"  state=directory recurse=yes owner={{ devops_docker_utils.user }} group={{ devops_docker_utils.user }}

- name: create docker-compose assemble dir
  file: path="{{ devops_docker_utils.compose_dir }}/assemble"  state=directory recurse=yes owner={{ devops_docker_utils.user }} group={{ devops_docker_utils.user }}

- name: copy consul template
  template: src=docker-compose-consul.yml dest="{{ devops_docker_utils.compose_dir }}/assemble/"  owner={{ devops_docker_utils.user }} group={{ devops_docker_utils.user }}
  when: devops_docker_utils.consul is defined
  tags: consul

- name: create consul config dir
  file: path="{{ devops_docker_utils.compose_dir }}/consul/config" state=directory recurse=yes owner={{ devops_docker_utils.user }} group={{ devops_docker_utils.user }}
  when: devops_docker_utils.consul is defined
  tags: consul

- name: copy consul config
  template: src=consul/config.json dest="{{ devops_docker_utils.compose_dir }}/consul/config/" owner={{ devops_docker_utils.user }} group={{ devops_docker_utils.user }}
  when: devops_docker_utils.consul is defined
  tags: consul

- name: copy registrator template
  template: src=docker-compose-registrator.yml dest="{{ devops_docker_utils.compose_dir }}/assemble/"  owner={{ devops_docker_utils.user }} group={{ devops_docker_utils.user }}
  when: devops_docker_utils.registrator is defined

- name: copy logspout template
  template: src=docker-compose-logspout.yml dest="{{ devops_docker_utils.compose_dir }}/assemble/"  owner={{ devops_docker_utils.user }} group={{ devops_docker_utils.user }}
  when: devops_docker_utils.logspout is defined

- name: assemble docker-compose files
  assemble: src="{{ devops_docker_utils.compose_dir }}/assemble/" dest="{{ devops_docker_utils.compose_dir }}/docker-compose.yml" owner={{ devops_docker_utils.user }} group={{ devops_docker_utils.user }}

#- name: docker-compose up
#  shell: /usr/bin/docker-compose up -d chdir="{{ devops_docker_utils.compose_dir }}"
