---
# tasks file for ansible-role-devops-docker-utils

- include: remove.yml

- name: create docker network
  shell: docker network create -d bridge --subnet={{ devops_docker_utils_docker_network_subnet }} {{ devops_docker_utils_docker_network }}
  when: devops_docker_utils_docker_network is defined
  ignore_errors: yes

- name: create docker-compose dir
  file: path="{{ devops_docker_utils.compose_dir }}"  state=directory recurse=yes owner={{ devops_docker_utils.user }} group={{ devops_docker_utils.user }}

- name: create docker-compose assemble dir
  file: path="{{ devops_docker_utils.compose_dir }}/assemble"  state=directory recurse=yes owner={{ devops_docker_utils.user }} group={{ devops_docker_utils.user }}

- name: copy start docker_compose
  template: src=start-docker-compose.yml dest="{{ devops_docker_utils.compose_dir }}/assemble/0_docker-compomse.yml"  owner={{ devops_docker_utils.user }} group={{ devops_docker_utils.user }}
  tags: docker_compose

- name: copy consul template
  template: src=docker-compose-consul.yml dest="{{ devops_docker_utils.compose_dir }}/assemble/1_consul.yml"  owner={{ devops_docker_utils.user }} group={{ devops_docker_utils.user }}
  when: devops_docker_utils.consul is defined and devops_docker_utils_consul_disable is undefined
  tags:
    - consul
    - docker_compose

- name: copy registrator template
  template: src=docker-compose-registrator.yml dest="{{ devops_docker_utils.compose_dir }}/assemble/1_registrator.yml"  owner={{ devops_docker_utils.user }} group={{ devops_docker_utils.user }}
  when: devops_docker_utils.registrator is defined and devops_docker_utils_registrator_disable is undefined
  tags:
    - registrator
    - docker_compose

- name: copy logspout template
  template: src=docker-compose-logspout.yml dest="{{ devops_docker_utils.compose_dir }}/assemble/1_logspout.yml"  owner={{ devops_docker_utils.user }} group={{ devops_docker_utils.user }}
  when: devops_docker_utils.logspout is defined and devops_docker_utils_logspout_disable is undefined
  tags:
    - logspout
    - docker_compose

- name: create consul-template templates
  include: service-discovery.yml
  when: devops_docker_utils.service_discovery is defined and devops_docker_utils_service_discovery_disable is undefined
  tags:
    - service_discovery
    - docker_compose

- name: copy end docker_compose with network
  template: src=end-docker-compose.yml dest="{{ devops_docker_utils.compose_dir }}/assemble/99_docker-compomse.yml"  owner={{ devops_docker_utils.user }} group={{ devops_docker_utils.user }}
  when: devops_docker_utils_docker_network is defined
  tags: docker_compose

- name: assemble docker-compose files
  assemble: src="{{ devops_docker_utils.compose_dir }}/assemble/" dest="{{ devops_docker_utils.compose_dir }}/docker-compose.yml" owner={{ devops_docker_utils.user }} group={{ devops_docker_utils.user }}
  tags: always

- include: pull.yml
  when: devops_docker_utils_just_pull is defined

- include: rolling_update.yml
  when: devops_docker_utils_just_pull is undefined
  tags: devops_docker_utils_rolling_update
