
    #logspout service runs in docker1 network by default
    logspout:
      container_name: devops_docker_utils_logspout
      image: gliderlabs/logspout:{{ devops_docker_utils.logspout.tag }}
      hostname: {{ hostname_replaced }}
      environment:
        SERVICE_NAME: logspout
      ports:
        - "{{ devops_docker_utils.logspout.ports }}"
      command: {{ devops_docker_utils.logspout.command }}
      restart: {{ devops_docker_utils.logspout.restart }}
      networks:
        - {{ devops_docker_utils_docker_network }}
      volumes:
         - /var/run/docker.sock:/tmp/docker.sock
