
    #logspout service runs in docker1 network by default
    logspout:
      container_name: logspout
      image: gliderlabs/logspout:{{ devops_docker_utils.logspout.tag }}
      hostname: {{ hostname_replaced }}
      environment:
        SERVICE_NAME: logspout
      ports:
        - "{{ devops_docker_utils.logspout.ports }}"
      command: {{ devops_docker_utils.logspout.command }}
      restart: {{ devops_docker_utils.logspout.restart }}
      volumes:
         - /etc/localtime:/etc/localtime:ro
         - /var/run/docker.sock:/tmp/docker.sock
