
service-discovery:
 image: aguamala/service-discovery:{{ devops_docker_utils.service-discovery.tag }}
 hostname: {{ hostname }}
 restart: {{ devops_docker_utils.service-discovery.restart }}
 volumes:
   - /var/run/docker.sock:/tmp/docker.sock
