
service-discovery:
 image: aguamala/service-discovery:{{ devops_docker_utils.service-discovery.tag }}
 hostname: {{ hostname }}
 restart: {{ devops_docker_utils.service-discovery.restart }}
 privileged: true
 {% for service in devops_docker_utils_service_discovery.templates  %}
 expose:
  - {{ service.port }}
 {% endfor %}
 volumes:
   - ./consul-template:/etc/consul-template
