
    #registrator runs in host's network
    #if wanted to run inside another network we have to set -ip option to force host's IP and add extra_hosts to resolve consul
    registrator:
     container_name: registrator
     image: gliderlabs/registrator:{{ devops_docker_utils.registrator.tag }}
     hostname: {{ hostname_replaced }}
     command: {{ devops_docker_utils.registrator.command }}
     restart: {{ devops_docker_utils.registrator.restart }}
     #network_mode: "host"
     extra_hosts:
       - "consul:{{ ansible_default_ipv4.address }}"
     depends_on:
       - consul
     volumes:
       - /etc/localtime:/etc/localtime:ro
       - /var/run/docker.sock:/tmp/docker.sock
