
service-discovery:
 image: aguamala/service-discovery:{{ devops_docker_utils.service_discovery.tag }}
 hostname: {{ hostname }}
 restart: {{ devops_docker_utils.service_discovery.restart }}
 privileged: true
 expose:
 {% for service in devops_docker_utils_service_discovery.templates  %}
  - {{ service.port }}
 {% endfor %}
 volumes:
   - ./consul-template:/etc/consul-template
