    
    #service-discovery service runs in docker1 network by default
    service-discovery:
     container_name: devops_docker_utils_service_discovery
     image: aguamala/service-discovery:{{ devops_docker_utils.service_discovery.tag }}
     hostname: elhost-172-20-10-227
     restart: {{ devops_docker_utils.service_discovery.restart }}
     privileged: true
     depends_on:
       - consul
     extra_hosts:
       - "consul:{{ ansible_default_ipv4.address }}"
     networks:
       - {{ devops_docker_utils_docker_network }}
     volumes:
       - ./consul-template:/etc/consul-template
     expose:
{% for service in devops_docker_utils_service_discovery.consul_template.templates  %}
      - {{ service.port }}
{% endfor %}
